Regenerate a new workout on the Workout page before saving
ATLAUS/Project-Hercules-React pull request #86
Opened 2024-08-20 04:12 UTC by danxguerrero

closes #83

2024-08-20 13:54 UTC, Aaron-G-Sanchez requested changes
Minor tweaks but otherwise nice!

2024-08-20 13:54 UTC, Aaron-G-Sanchez commented on __tests__/routes/workout/Workout.test.jsx
> +  fetchNewGeminiWorkout: vi.fn()
For reference on the comment below about setting the resolved value here.

[Saved-workout test](https://github.com/ATLAUS/Project-Hercules-React/blob/27e81c588f62404a469c1dbe727aeadb1967937e/__tests__/routes/saved-workout/SavedWorkout.test.jsx#L41)

2024-08-20 13:54 UTC, Aaron-G-Sanchez commented on __tests__/routes/workout/Workout.test.jsx
> +describe('Regenerate a new workout', () => {
Since these tests are using the same data as the describe block above, can these tests be moved into that block as well? A) to consolidate code and B) I think the use cases being tested would fall under the broader scope of the workout component rendering a generated workout. 

This can be done later but I think the very first test in that describe block should validate that all things expected to render WOULD render and I believe the `regeneration button` would fall into that.

2024-08-20 17:38 UTC, danxguerrero commented on __tests__/routes/workout/Workout.test.jsx
> +  fetchNewGeminiWorkout: vi.fn()
Done.

2024-08-20 17:43 UTC, danxguerrero commented on __tests__/routes/workout/Workout.test.jsx
> +    })
Done.

2024-08-21 02:33 UTC, Aaron-G-Sanchez requested changes
LGTM!

2024-08-21 02:33 UTC, Aaron-G-Sanchez commented on __tests__/routes/workout/Workout.test.jsx
>      const mockFetchNewGeminiWorkout = fetchNewGeminiWorkout
Because you are mocking the value return of fetchNewGeminiWorkout, I think you can say expect(fetchNewGeminiWorkout).toHaveBeenCalledTimes(1) like the old test. As of now I don't think this is being used. Could also remove if you wanted.

2024-08-21 22:28 UTC, danxguerrero commented on __tests__/routes/workout/Workout.test.jsx
>      const mockFetchNewGeminiWorkout = fetchNewGeminiWorkout
Done! I removed the expect.toHaveBeenCalledTimes and just left the second expect with the parameters that we want the actual function to be called with.

2024-08-22 02:33 UTC, Aaron-G-Sanchez approved these changes
NOICE! LGTM 🪨

2024-08-22 02:33 UTC, merged